// Generated by https://quicktype.io

export interface Project {
  id: string
  programa: Programa
  title: string
  description?: string
  completed: boolean
  year: number
  authors: Author[]
  urlResumen?: string
  urlProject?: string
  departamentos?: string[]
  tags?: Tag[]
  convenios?: Convenio[]
}

export interface Author {
  name: string
  email: string
}

export interface Convenio {
    id: string
    name: string
    description?: string
    
  }

  export interface Programa {
    id: string
    name: string
    description?: string
    
  }

  export interface Tag {
    id: string
    name: string
  }
